### ISSUE TITLE
Exercise3

### ISSUE THREAD

**Issue by nadejdashed** [mohanakrishnag/Native-JS#11]
Almost all nice, except prefill-an-array.js:
- for (var i = 0; i < times; i++) you know that "times" could be string so please parse it explicitly

**Comment by mohanakrishnag** [comment]
@nadejdashed Fixed the review comments

**Comment by nadejdashed** [comment]
Be careful with the second action in for loop. parseInt(times) will be calculated every loop. Please move it out of loop.

**Comment by mohanakrishnag** [comment]
Fixed
