### ISSUE TITLE
Exercise4

### ISSUE THREAD

**Issue by nadejdashed** [mohanakrishnag/Native-JS#12]
Great, but please finish one more task - http://www.codewars.com/kata/using-closures-to-share-class-state

**Comment by mohanakrishnag** [comment]
@nadejdashed I have missed it. completed now, please verify

**Comment by nadejdashed** [comment]
@mohanakrishnag,

Add Array.prototype.awerageWeight will affect all Arrays. The method awerageWeight  will appear in all arrays. Prevent to do it. Please correct it.

**Comment by mohanakrishnag** [comment]
Fixed.
